compatibility_date = "2023-12-06"
main = "release/index.js"
name = "memoize-worker"
send_metrics = false

[build]
command = "yarn build"
watch_dir = "src"

[dev]
ip = "localhost"
port = 5000

[site]
bucket = "assets"
